### Recuperar todos los diputados.
GET http://localhost:4000/api/deputies/

### Recuperar todos los diputados de una provincia.
GET http://localhost:4000/api/deputies/habana

### Para crear un deputies.
POST http://localhost:4000/api/deputies/
Content-Type: application/json

{
    "name": "Jose Luis Hernandez",
    "age": 29,
    "image": "https://localhost:4000/deputies/1/image1.jpg",
    "town": "Consolación del Sur",
    "position": "Vendedor de Churros",
    "biography": "fdnvbsdbiufviafdvbiabfivbafibviadfvbiadfvbihabdvfhibadhvbahdbvfhad"
}

### Para actualizar un deputies
PUT http://localhost:4000/api/deputies/1
Content-Type: application/json

{
    "age": 30,
    "position": "Vendedor de Mani"
}

### Para eliminar un deputies
DELETE http://localhost:4000/api/deputies/1
