### Recuperar todos los diputados.
GET http://localhost:4000/api/deputies/


### Recuperar todos los diputados de una provincia.
GET http://localhost:4000/api/deputies/habana


### Para crear un deputies.
POST http://localhost:4001/api/deputies/
Content-Type: application/json

{
    "name": "Jose Luis Hernandez",
    "age": 29,
    "hola:": "imagen",
    "province": "Pinar del Rio",
    "town": "Bahia Honda",
    "position": "Vendedor de Churros",
    "biography": "fdnvbsdbiufviafdvbiabfivbafibviadfvbiadfvbihabdvfhibadhvbahdbvfhad"
}


### Para actualizar un deputies
PATCH http://localhost:4000/api/deputies/1
Content-Type: application/json

{
    "age": 30,
    "position": "Vendedor de Mani"
}

### Para eliminar un deputies
DELETE http://localhost:4000/api/deputies/1
