### Recuperar todos los votantes de {Municipio} de la {Provincia}.
GET http://localhost:4000/api/voters/lahabana/guanabacoa

### Para crear un Votante.
POST http://localhost:4000/api/voters/
Content-Type: application/json

{
    "name": "Jose Luis Hernandez",
    "age": 29,
    "CI": "02049567546",
    "province": "Pinar del Rio",
    "town": "Consolación del Sur"
}

### Para actualizar un Votante
PUT http://localhost:4000/api/voters/1
Content-Type: application/json

{
  "name": "Jose Luis Hernandez",
  "age": 29,
  "CI": "02049567546",
  "province": "Pinar del Rio",
  "town": "Consolación del Sur",
  "isValidVoter": {
      "status": true,
      "reason": ""
  }
}

### Para eliminar un Votante
DELETE http://localhost:4000/api/voters/1
